-- Migration: create table featured_products
-- Run this in Supabase SQL editor or via psql

CREATE TABLE IF NOT EXISTS featured_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  added_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_by TEXT -- optionnel: admin id/email
);

CREATE INDEX IF NOT EXISTS idx_featured_products_product_id ON featured_products(product_id);
